[project]
name = "frt"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "dan-german", email = "dangerman909@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "librosa>=0.11.0",
    "numpy>=2.2.0",
    "pyqt6>=6.11.0",
    "pyqtgraph>=0.14.0",
    "soundfile>=0.14.0",
    "sounddevice>=0.5.0",
]

[project.scripts]
frt = "frt.app:main"
frt-generate-dataset = "frt.dataset.cli:main"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
