SAMPLE_RATE = 44100
MAX_SAMPLE_SECONDS = 4
MAX_SAMPLE_SAMPLES = MAX_SAMPLE_SECONDS * SAMPLE_RATE

WINDOW_WIDTH = 1200
WINDOW_HEIGHT = 900
PLOT_HEIGHT = 40
WAVEFORM_WIDTH = 1000

DRAG_PIXELS_TO_SAMPLES = 40
ANALYSIS_UPDATE_DELAY_MS = 35

DEFAULT_FRETTING = (0, 0, None, None, None, None)

